{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "quickstart"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword }}
{{- $databaseName := .Values.global.secrets.databaseName| default "quickstart" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser $databasePassword $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser $databasePassword $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  SERVER_KC_CLIENTID: {{ .Values.global.secrets.SERVER_KC_CLIENTID | b64enc | quote }}
  SERVER_KC_CLIENTSECRET: {{ .Values.global.secrets.SERVER_KC_CLIENTSECRET | b64enc | quote }}
  SC_CS_CHES_CLIENT_ID: {{ .Values.global.secrets.SC_CS_CHES_CLIENT_ID | b64enc | quote }}
  SC_CS_CHES_CLIENT_SECRET: {{ .Values.global.secrets.SC_CS_CHES_CLIENT_SECRET | b64enc | quote }}
  SC_CS_CDOGS_CLIENT_ID: {{ .Values.global.secrets.SC_CS_CDOGS_CLIENT_ID | b64enc | quote }}
  SC_CS_CDOGS_CLIENT_SECRET: {{ .Values.global.secrets.SC_CS_CDOGS_CLIENT_SECRET | b64enc | quote }}
  FILES_OBJECTSTORAGE_ACCESSKEYID: {{ .Values.global.secrets.FILES_OBJECTSTORAGE_ACCESSKEYID | b64enc | quote }}
  FILES_OBJECTSTORAGE_SECRETACCESSKEY: {{ .Values.global.secrets.FILES_OBJECTSTORAGE_SECRETACCESSKEY | b64enc | quote }}
  APITOKEN: {{ .Values.global.secrets.APITOKEN | b64enc | quote }}
{{- end }}
